# Generated by Django 2.2 on 2020-09-17 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0002_auto_20200917_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='description',
        ),
        migrations.RemoveField(
            model_name='city',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='city',
            name='temperature',
        ),
    ]
